/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import handler.NodeHandler;
import nodes.NodeException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.Font;
import java.util.Map;

/**
 * @author user
 */
public class FormMain extends JFrame implements DocumentListener {

    private transient NodeHandler nodeHandler;

    private static final String ERROR_TITLE = "Error";

    public FormMain() {
        initComponents();
        setSelectedCaffePrice();
        setListener();
        createNodeHandler();
        setCloseOperation();
    }

    private void createNodeHandler() {
        nodeHandler = new NodeHandler();
    }

    private void setCloseOperation() {
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrb20 = new javax.swing.JRadioButton();
        jrb25 = new javax.swing.JRadioButton();
        jrb30 = new javax.swing.JRadioButton();
        jrb40 = new javax.swing.JRadioButton();
        jrb50 = new javax.swing.JRadioButton();
        jLabelPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabelAmountMessage = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtReturns = new javax.swing.JTextField();
        jLabelReturnsMessage = new javax.swing.JLabel();
        btnMake = new javax.swing.JButton();
        jLabel100 = new javax.swing.JLabel();
        txt100 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txt50 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt20 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabelChangeMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Coffee machine");

        buttonGroup1.add(jrb20);
        jrb20.setSelected(true);
        jrb20.setText("Espresso(20)");
        jrb20.addActionListener(this::jrb20ActionPerformed);

        buttonGroup1.add(jrb25);
        jrb25.setText("Espresso with milk (25)");
        jrb25.addActionListener(this::jrb25ActionPerformed);

        buttonGroup1.add(jrb30);
        jrb30.setText("Cappuccino (30)");
        jrb30.addActionListener(this::jrb30ActionPerformed);

        buttonGroup1.add(jrb40);
        jrb40.setText("Irish coffee (40)");
        jrb40.addActionListener(this::jrb40ActionPerformed);

        buttonGroup1.add(jrb50);
        jrb50.setText("Hot chocolate (50)");
        jrb50.addActionListener(this::jrb50ActionPerformed);

        jLabelPrice.setText("Price:");

        txtPrice.setEditable(false);
        final Font font = new Font("Default", Font.BOLD, 48);
        txtPrice.setFont(font);

        jLabelAmountMessage.setText("Amount:");

        txtAmount.setFont(font);

        txtReturns.setEditable(false);
        txtReturns.setFont(font);

        jLabelReturnsMessage.setText("Returns:");

        btnMake.setText("Make coffee!");
        btnMake.addActionListener(this::btnMakeActionPerformed);

        jLabel100.setText("100");

        txt100.setEditable(false);

        jLabel50.setText("50");

        txt50.setEditable(false);

        jLabel10.setText("10");

        txt20.setEditable(false);

        jLabel1.setText("1");

        txt1.setEditable(false);

        jLabelChangeMessage.setText("Returned changed in denomination:");

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jrb20)
                                                                        .addComponent(jrb25)
                                                                        .addComponent(jrb30)
                                                                        .addComponent(jrb40)
                                                                        .addComponent(jrb50))
                                                                .addGap(88, 135, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabelPrice)
                                                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(19, 19, 19)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabelAmountMessage)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(10, 10, 10)
                                                                                .addComponent(txtAmount)
                                                                                .addGap(28, 28, 28))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jLabelChangeMessage)
                                                                .addGap(28, 28, 28)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelReturnsMessage)
                                                        .addComponent(txtReturns, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel50)
                                                                        .addComponent(jLabel10)
                                                                        .addComponent(jLabel1))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel100)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(btnMake, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jrb20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabelAmountMessage)
                                                .addComponent(jLabelPrice))
                                        .addComponent(jLabelReturnsMessage))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtReturns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelChangeMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel100))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel50))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(28, 28, 28)
                                .addComponent(btnMake)
                                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb30ActionPerformed(final java.awt.event.ActionEvent evt) {
        setSelectedCaffePrice();
    }

    private void jrb20ActionPerformed(final java.awt.event.ActionEvent evt) {
        setSelectedCaffePrice();
    }

    private void jrb25ActionPerformed(final java.awt.event.ActionEvent evt) {
        setSelectedCaffePrice();
    }

    private void jrb40ActionPerformed(final java.awt.event.ActionEvent evt) {
        setSelectedCaffePrice();
    }

    private void jrb50ActionPerformed(final java.awt.event.ActionEvent evt) {
        setSelectedCaffePrice();
    }

    private void btnMakeActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeActionPerformed
        try {
            checkEnoughMoney();
            final Map<String, Integer> banknoteChain =
                    nodeHandler.handle(Integer.parseInt(txtReturns.getText().trim()));
            txt100.setText(String.valueOf(banknoteChain.get("100")));
            txt50.setText(String.valueOf(banknoteChain.get("50")));
            txt20.setText(String.valueOf(banknoteChain.get("10")));
            txt1.setText(String.valueOf(banknoteChain.get("1")));
            JOptionPane.showMessageDialog(this, "Successfully created coffee!", "Coffee",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (final NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "You did not insert valid money amount!",
                    ERROR_TITLE,
                    JOptionPane.ERROR_MESSAGE);
        } catch (final Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    ERROR_TITLE, JOptionPane.ERROR_MESSAGE);
        }
    }


    private javax.swing.JButton btnMake;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelAmountMessage;
    private javax.swing.JLabel jLabelReturnsMessage;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChangeMessage;
    private javax.swing.JRadioButton jrb20;
    private javax.swing.JRadioButton jrb25;
    private javax.swing.JRadioButton jrb30;
    private javax.swing.JRadioButton jrb40;
    private javax.swing.JRadioButton jrb50;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt100;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt50;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtReturns;

    private void setSelectedCaffePrice() {
        clearFields();

        if (jrb20.isSelected()) {
            txtPrice.setText("20");
        }
        if (jrb25.isSelected()) {
            txtPrice.setText("25");
        }
        if (jrb30.isSelected()) {
            txtPrice.setText("30");
        }
        if (jrb40.isSelected()) {
            txtPrice.setText("40");
        }
        if (jrb50.isSelected()) {
            txtPrice.setText("50");
        }

    }

    private void setListener() {
        txtAmount.getDocument().addDocumentListener(this);
    }

    @Override
    public void insertUpdate(final DocumentEvent e) {
        setChange();
    }

    private void setChange() {
        final int coffeePrice =
                Integer.parseInt(txtPrice.getText());
        final int insertAmount = Integer.parseInt(txtAmount.getText());
        final int change = insertAmount - coffeePrice;
        txtReturns.setText(String.valueOf(change));
    }

    @Override
    public void removeUpdate(final DocumentEvent e) {
        try {
            setChange();
        } catch (final NumberFormatException numberFormatException) {
            System.out.println("Number format Exception " +
                    numberFormatException.getMessage());
        }
    }

    @Override
    public void changedUpdate(final DocumentEvent e) {
        throw new UnsupportedOperationException();
    }

    private void clearFields() {
        txt100.setText("");
        txt50.setText("");
        txt20.setText("");
        txt1.setText("");
        txtReturns.setText("");
        txtAmount.repaint();
        txtAmount.setText("");
    }

    private void checkEnoughMoney() throws NodeException {
        if (txtAmount.getText().isEmpty()) {
            throw new NodeException("You did not insert money!");
        }
        final int insertAmount = Integer.parseInt(txtAmount.getText().trim());
        final int selectedCoffeePrice =
                Integer.parseInt(txtPrice.getText().trim());

        if (insertAmount < selectedCoffeePrice) {
            throw new NodeException("You did not insert enough money!");
        }
    }
}
